name: golang-ci
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  setup:
    name: setup
    runs-on: ubuntu-20.04
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.7
        id: go
      - name: check out
        uses: actions/checkout@v2

      # 処理を高速化するために環境をキャッシュ
      # 参照：https://github.com/mvdan/github-actions-golang
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  build:
    name: build
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: go build ./...

  test:
    name: test
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: go test ./... -v
  
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35.2
          args: --config=.golangci.yml --fast
